language: php
dist: trusty

cache:
  directories:
    - .cache
    - vendor
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

branches:
  only:
    - master
    - /^release\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/

php:
  - 7.0
  - 5.6
  - "nightly"

jobs:
  fast_finish: true
  include:
    - php: 7.4
      env: PHPCS=1

  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

install:
  - if [[ $PHPCS == "1" ]]; then composer install --prefer-dist --no-interaction; fi

script:
# PHP Linting
- if find -L . -path ./vendor -prune -o -path ./node_modules -prune -o -name '*.php' -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi

# Validate the composer.json file.
# @link https://getcomposer.org/doc/03-cli.md#validate
- if [[ $TRAVIS_PHP_VERSION == "5.6" || $TRAVIS_PHP_VERSION == "7.4" ]]; then composer validate --no-check-all; fi

# Check the code against YoastCS.
- if [[ $PHPCS == "1" ]]; then vendor/bin/phpcs -q; fi
