os: linux
language: php

cache:
  directories:
    - vendor
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

branches:
  only:
    - master
    - /^release\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/

php:
  - 8.0
  - 7.4
  - 7.0
  - 5.6

jobs:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

install:
  - |
    if [[ $TRAVIS_PHP_VERSION == "nightly" ]]; then
      composer install --prefer-dist --no-interaction --ignore-platform-reqs
    else
      composer install --prefer-dist --no-interaction
    fi

script:
# PHP Linting
- composer lint
